version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - 'VanOns/open-source'

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - 'VanOns/open-source'
